Traceback (most recent call last):
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/frmuno/anaconda3/envs/jupyterbook/lib/python3.8/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
l15af = l15a[l15a["fase"] == "Vota√ß√£o na generalidade"]
l15af["GP"] = l15af["iniAutorGruposParlamentares"]
l15af = l15af[l15af["GP"].notna()]

l14af["iniAutorGruposParlamentares"]  = l14af["iniAutorGruposParlamentares"].replace("JOACINE KATAR MOREIRA", "L")
l14af = l14a[l14a["fase"] == "Vota√ß√£o na generalidade"]
l14af["GP"] = l14af["iniAutorGruposParlamentares"]
l14af = l14af[l14af["GP"].notna()]


------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m/tmp/ipykernel_157585/4077841856.py[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0ml15af[0m [0;34m=[0m [0ml15af[0m[0;34m[[0m[0ml15af[0m[0;34m[[0m[0;34m"GP"[0m[0;34m][0m[0;34m.[0m[0mnotna[0m[0;34m([0m[0;34m)[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0;34m[0m[0m
[0;32m----> 5[0;31m [0ml14af[0m[0;34m[[0m[0;34m"iniAutorGruposParlamentares"[0m[0;34m][0m  [0;34m=[0m [0ml14af[0m[0;34m[[0m[0;34m"iniAutorGruposParlamentares"[0m[0;34m][0m[0;34m.[0m[0mreplace[0m[0;34m([0m[0;34m"JOACINE KATAR MOREIRA"[0m[0;34m,[0m [0;34m"L"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      6[0m [0ml14af[0m [0;34m=[0m [0ml14a[0m[0;34m[[0m[0ml14a[0m[0;34m[[0m[0;34m"fase"[0m[0;34m][0m [0;34m==[0m [0;34m"Vota√ß√£o na generalidade"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m
[1;32m      7[0m [0ml14af[0m[0;34m[[0m[0;34m"GP"[0m[0;34m][0m [0;34m=[0m [0ml14af[0m[0;34m[[0m[0;34m"iniAutorGruposParlamentares"[0m[0;34m][0m[0;34m[0m[0;34m[0m[0m

[0;31mNameError[0m: name 'l14af' is not defined
NameError: name 'l14af' is not defined

